server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  application:
    name: waveform-analysis-platform
  # MySQL 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/waveform_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456 # 替换为本地数据库密码
  # Redis 配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      # password: # redis密码
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB  # 单个文件允许的最大上限
      max-request-size: 100MB  # 单次HTTP请求的总大小上限

  # springai
  ai:
    # 1. 本地 Ollama 配置
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.6

    # 2. 阿里云百炼配置（OpenAI 规范）
    openai:
      # 百炼官方的 OpenAI 兼容标准网关地址
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      # 阿里云百炼控制台申请的密钥
      api-key: sk-*******************
      chat:
        options:
          # 指定模型
          model: qwen3.7-plus
          temperature: 0.6


# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml  # XML 文件存放位置
  type-aliases-package: com.nan.waveform.*.domain.entity # 实体类包名，方便 XML 里直接写类名
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动映射 (user_name -> userName)

# 自定义 JWT 配置
jwt:
  secret: waveform_nan_secret_key_2026!@#
  expiration: 86400 # token 过期时间，单位秒 (1天)

# 日志打印
logging:
  level:
    com.alibaba.excel.metadata.format.DataFormatter: OFF
    # 让 Spring AI 官方的 Advisor 切面直接在控制台输出会话日志
    org.springframework.ai.chat.client.advisor: DEBUG


# module-waveform-vision模块的配置参数
waveform-vision:
  # 三相裁剪区域 (ROI)
  roi:
    phase-a: { x: 55, y: 56, w: 1400, h: 310 }    # A相默认物理裁剪矩形
    phase-b: { x: 55, y: 370, w: 1400, h: 310 }   # B相默认物理裁剪矩形
    phase-c: { x: 55, y: 683, w: 1400, h: 310 }   # C相默认物理裁剪矩形
    jieyue: { x: 58, y: 456, w: 980, h: 147 }     # 阶跃响应时间专属裁剪矩形
  # HSV颜色
  hsv:
    green:
      low: [35, 60, 50]
      high: [85, 255, 255]
    blue:
      low: [100, 80, 60]
      high: [130, 255, 255]